### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [OpenHAK/OpenHAK_Firmware#2]
Hi, I noticed that all the `Wire.requestFrom()` are followed by a `Wire.endTransmission()`, but the `Wire.endTransmission()` should only be used when writing data.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by biomurph** [comment]
I think I put those in while exploring a troubleshooting rabbit hole.
Good to know that the Wire.requestFrom manages all of that handshaking.
